### ISSUE TITLE
Emergency priority Pushover notifications

### ISSUE THREAD

**Issue by jason-doyle-sr** [daleghent/nina-plugins#3]
In order to ensure that pushover sounds wake me if needed during the night, it'd be nice to have emergency priority available so that they require me to acknowledge before they're dismissed. 
I noticed in the code that emergency priority was explicitly left out of the array. Can these be added, or are they not used for a reason? Thanks.

**Comment by daleghent** [comment]
The `Emergency` priority is omitted because the PushoverNET client library that I use in GS does not support the extra `retry` and `expires` parameters that must be supplied along with a message that has that specific priority. Messages that are submitted to the Pushover API at that priority but without those parameters will fail, hence it is removed from the list.

I'll look at replacing PushoverNET with a different library that has this capability when I get the time to do so.

**Comment by daleghent** [comment]
This is still on the to-do list, but I've moved Ground Station to [its own repo](https://github.com/daleghent/nina-ground-station)
